### ISSUE TITLE
Film Grain DCTL

### ISSUE THREAD

**Issue by decayedxistence** [thatcherfreeman/utility-dctls#7]
![Screenshot 2024-06-30 at 12 23 01 PM](https://github.com/thatcherfreeman/utility-dctls/assets/172299594/7d38c3a1-b1dc-4055-9a80-29456df21dd7)

Using Resolve 19 Studio Beta 4 with the Film Grain DCTL.

When I set up the pipeline of duplicating the DCTL for negative/positve, It causes an output blanking issue that crops into the image but also.changes the black letterbox to white.

I noticed it's been a year since the DCTL has been updated so it may need some tweaks.

Thanks!

**Comment by thatcherfreeman** [comment]
Hey, I've just made a small change to the Film Grain (and also the Photon Noise) DCTLs to clamp off negative inputs, which were poorly behaving. Please download the update and you should see that the issue is resolved. The update should not break any of your grades.

**Comment by decayedxistence** [comment]
Appreciate it, Thatcher. I closed this issue because Chad was helping and talking to you over on the BM forums. Will let you know if any issues persist. Thanks so much!
